name: Continuous Integration / Continuous Deployment
on:
  push:
    branches:
    - module-8
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
jobs:
  build:
    name: Build the image and test it...
    runs-on: ubuntu-latest
    steps:
    - name: checkout stage
      uses: actions/checkout@v3
    - name: building the image
      run: docker build --target test --tag test-image-v1 .
    - name: running the test
      run: docker run test-image-v1

  dockerhub:
    name: Build an image to docker hub...
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'module-9'
    steps:
    - run: echo 'Publishing...'
    - uses: actions/checkout@v2

    - name: Login to docker hub...
      run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login --username francescowang --password-stdin
    
    - name: Build docker image...
      run: docker build -t francescowang/todoapp .
    
    - name: Push image to docker hub...
      run: docker push francescowang/todoapp
    
    - name: Publish website...
      run: curl -dH -X POST ${{secrets.WEBHOOK_URL}}

