name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build the image and test it...
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --target test --tag test-image-v1 .
    - run: docker run test-image-v1